// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/abrir-cnpj" | "/auth/callback" | "/blog" | "/blog/[slug]" | "/cadastro" | "/clientes" | "/contabilidade" | "/ferramentas/calculadora-precificacao" | "/ferramentas/gerador-contrato" | "/ferramentas/simulador-contratacao" | "/ferramentas/simulador-rescisao" | "/hub" | "/login" | "/onboarding-clientes" | "/pfx" | "/redefinir-senha" | "/solicitacoes-clientes"
type AppRouteHandlerRoutes = "/api/admin/onboarding/[id]/reveal-senha" | "/api/auth/email-change" | "/api/auth/password-reset" | "/api/contabilidade/enviar-rotinas" | "/api/hub/profile" | "/api/onboarding/contato-presumido" | "/api/onboarding/intake" | "/api/onboarding/start-mei" | "/api/stripe/checkout" | "/api/stripe/checkout-product" | "/api/stripe/portal" | "/api/stripe/webhook" | "/api/tool-usage"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/abrir-cnpj": {}
  "/api/admin/onboarding/[id]/reveal-senha": { "id": string; }
  "/api/auth/email-change": {}
  "/api/auth/password-reset": {}
  "/api/contabilidade/enviar-rotinas": {}
  "/api/hub/profile": {}
  "/api/onboarding/contato-presumido": {}
  "/api/onboarding/intake": {}
  "/api/onboarding/start-mei": {}
  "/api/stripe/checkout": {}
  "/api/stripe/checkout-product": {}
  "/api/stripe/portal": {}
  "/api/stripe/webhook": {}
  "/api/tool-usage": {}
  "/auth/callback": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/cadastro": {}
  "/clientes": {}
  "/contabilidade": {}
  "/ferramentas/calculadora-precificacao": {}
  "/ferramentas/gerador-contrato": {}
  "/ferramentas/simulador-contratacao": {}
  "/ferramentas/simulador-rescisao": {}
  "/hub": {}
  "/login": {}
  "/onboarding-clientes": {}
  "/pfx": {}
  "/redefinir-senha": {}
  "/solicitacoes-clientes": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
