// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/abrir-cnpj/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/abrir-cnpj">> = Specific
  const handler = {} as typeof import("../../app/abrir-cnpj/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../app/cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../app/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contabilidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contabilidade">> = Specific
  const handler = {} as typeof import("../../app/contabilidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ferramentas/calculadora-precificacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/calculadora-precificacao">> = Specific
  const handler = {} as typeof import("../../app/ferramentas/calculadora-precificacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ferramentas/gerador-contrato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/gerador-contrato">> = Specific
  const handler = {} as typeof import("../../app/ferramentas/gerador-contrato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ferramentas/simulador-contratacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/simulador-contratacao">> = Specific
  const handler = {} as typeof import("../../app/ferramentas/simulador-contratacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ferramentas/simulador-rescisao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/simulador-rescisao">> = Specific
  const handler = {} as typeof import("../../app/ferramentas/simulador-rescisao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../app/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding-clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding-clientes">> = Specific
  const handler = {} as typeof import("../../app/onboarding-clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pfx/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pfx">> = Specific
  const handler = {} as typeof import("../../app/pfx/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/redefinir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../app/redefinir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/solicitacoes-clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solicitacoes-clientes">> = Specific
  const handler = {} as typeof import("../../app/solicitacoes-clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/onboarding/[id]/reveal-senha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/onboarding/[id]/reveal-senha">> = Specific
  const handler = {} as typeof import("../../app/api/admin/onboarding/[id]/reveal-senha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/email-change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/email-change">> = Specific
  const handler = {} as typeof import("../../app/api/auth/email-change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/password-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password-reset">> = Specific
  const handler = {} as typeof import("../../app/api/auth/password-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contabilidade/enviar-rotinas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contabilidade/enviar-rotinas">> = Specific
  const handler = {} as typeof import("../../app/api/contabilidade/enviar-rotinas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hub/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hub/profile">> = Specific
  const handler = {} as typeof import("../../app/api/hub/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/contato-presumido/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/contato-presumido">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/contato-presumido/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/intake">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/start-mei/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/start-mei">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/start-mei/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout-product">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tool-usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tool-usage">> = Specific
  const handler = {} as typeof import("../../app/api/tool-usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
